### ISSUE TITLE
Help with missing documentation

### ISSUE THREAD

**Issue by bratpeki** [freeglut/freeglut_website#3]
Greetings!

I've taken an interest into FreeGLUT and wish to write a small GUI library with it, in an attempt to learn OpenGL!

I'm writing to ask if any help regarding the missing [API docs](https://freeglut.sourceforge.net/docs/api.php) is welcome, since I could work on it while making my own project!

TY!

**Comment by dcnieho** [comment]
Hi Petar,

Glad to hear. Certainly, a contribution to that in the form of a pull
request is always welcome!

All the best

**Comment by bratpeki** [comment]
Thank you for the quick reply! 😎

Would you be willing to except a draft PR, where we could work on it incrementally? Each missing element could be checked one at a time, as they're coming in.

Also, to note, I'm building on Win10, and hoping to build on Linux soon, since I'm waiting on my Linux machine to be fixed.

**Comment by jtsiomb** [comment]
Absolutely, it doesn't even have to be the whole documentation in a single pull request. We could merge it bit by bit through multiple pull requests, whatever makes it easier for you.

As for linux vs windows, it shouldn't really make any difference.

**Comment by jtsiomb** [comment]
Also to be honest I'm not sure we should necessarily stick to the same format we have now for the documentation. If you're up to it, I think it would be better to convert it to mark down, have it live in a `doc/` directory inside the main freeglut repo, and generate html from that for the website.
Just a thought.

**Comment by bratpeki** [comment]
Love the idea!

I've prior experience mainly with [Markdown](https://github.com/bratpeki/modern-milkytracker-guide) and [AsciiDoc](https://github.com/zynaddsubfx/user-manual/pull/22), which is optimal.

Also, I recall dabbling with FreeGLUT before and the way I ensured I've offline documentation was `Ctrl+S`-ing the API HTML page (LOL), so a Markdown doc directly in the base repo is definitely something I'm definitely down for! 😎

We could work on the doc bit by bit, or in one draft that is worked on in parts, I'm fine with both.

**Comment by jtsiomb** [comment]
I think bit by bit is easier both to write and to review. Not necessarily like one function at a time, but I guess small chunks of it.

**Comment by bratpeki** [comment]
Alright! We could do rewrites of existing documentation, per section, and
then addition of new content, also per section.

**Comment by SteveBaker** [comment]
I would recommend using Doxygen - that way documentation is inside the 
code itself.

---

On 2024-12-27 00:08, John Tsiombikas wrote:

> Also to be honest I'm not sure we should necessarily stick to the same 
> format we have now for the documentation. If you're up to it, I think 
> it would be better to convert it to markdown, have it live in a doc/ 
> directory inside the main freeglut repo, and generate html from that 
> for the website.
> Just a thought.
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].
> You are receiving this because you are subscribed to this 
> thread.Message ID: 
> ***@***.***>


Links:
------
[1] 
https://github.com/freeglut/freeglut_website/issues/3#issuecomment-2563396554
[2]

**Comment by jtsiomb** [comment]
I hate doxygen.

**Comment by bratpeki** [comment]
https://github.com/bratpeki/freeglut/blob/master/doc/api.md

Looking nice, eh? :)

I'm generally busy with college, so this would move pretty slow, but I'll try to work whenever possible!

**Comment by bratpeki** [comment]
Should this be one big Markdown file?

I feel like that should be more managable than multiple smaller ones, since that approach would require a lot of going back-and-forth.

**Comment by jtsiomb** [comment]
I don't think I have a strong opinion single vs multiple at this stage. Do whatever feels best. Probably single file is best as long as it doesn't get unwieldy.

That looks good. Try to keep the markdown source as readable as possible, so that the docs are usable from the source tree directly, even without translating to html.

Looking at this TOC, one thing I think might be useful, is to clearly indicate which functions are freeglut extensions (in `freeglut_ext.h`), and which ones are in standard GLUT. I don't know how to indicate that exactly. Ideally it should be something unobtrusive. The only thing I can think of is a small "[ext]" tag next to the name of the functions which are extensions, but if you can think of something better feel free to experiment.

Don't worry about how long it takes; take your time. It's very useful, but not urgent. We've made do with the existing half-baked API docs for years.

**Comment by bratpeki** [comment]
We could italicize the extended ones maybe, or add an "*", or "[ext]", as you suggested. We'll see

**Comment by bratpeki** [comment]
Looking into `freeglut_ext.h` for functions gives me this list, which I hope is 100% correct, as the cleanup process was semi-automated:

```
glutMainLoopEvent
glutLeaveMainLoop
glutExit
glutFullScreenToggle
glutLeaveFullScreen
glutSetMenuFont
glutMouseWheelFunc
glutPositionFunc
glutCloseFunc
glutWMCloseFunc
glutMenuDestroyFunc
glutSetOption
glutGetModeValues
glutGetWindowData
glutSetWindowData
glutGetMenuData
glutSetMenuData
glutBitmapHeight
glutStrokeHeight
glutBitmapString
glutStrokeString
glutWireRhombicDodecahedron
glutSolidRhombicDodecahedron
glutWireSierpinskiSponge
glutSolidSierpinskiSponge
glutWireCylinder
glutSolidCylinder
glutWireTeacup
glutSolidTeacup
glutWireTeaspoon
glutSolidTeaspoon
glutGetProcAddress
glutMultiEntryFunc
glutMultiButtonFunc
glutMultiMotionFunc
glutMultiPassiveFunc
glutJoystickGetNumAxes
glutJoystickGetNumButtons
glutJoystickNotWorking
glutJoystickGetDeadBand
glutJoystickSetDeadBand
glutJoystickGetSaturation
glutJoystickSetSaturation
glutJoystickSetMinRange
glutJoystickSetMaxRange
glutJoystickSetCenter
glutJoystickGetMinRange
glutJoystickGetMaxRange
glutJoystickGetCenter
glutInitContextVersion
glutInitContextFlags
glutInitContextProfile
glutInitErrorFunc
glutInitWarningFunc
glutSetVertexAttribCoord3
glutSetVertexAttribNormal
glutSetVertexAttribTexCoord2
glutInitContextFunc
glutAppStatusFunc
```

Are all of these function that are not in GLUT?

**Comment by jtsiomb** [comment]
There's also the "ucall" functions in a separate header file included at the bottom of freeglut_ext.h

**Comment by bratpeki** [comment]
Sure thing, that's already in practice, so no work need be done!

I'll try forming the list of functions first, and make an appropriate PR for that, where we can discuss the docs onward. Is this fit for closing, then?

**Comment by jtsiomb** [comment]
sure
